### ISSUE TITLE
info parameters to put things in in sam

### ISSUE THREAD

**Issue by hschellman** [DUNE/NTupleProd#9]
```
info.memory (true_int)
info.cpusec (true_float)
info.wallsec (true_float)
info.physicsgroup (string)
now exist.  Your Physics group is dunepdhd
```

**Comment by calcuttj** [comment]
Done. See [here](https://github.com/DUNE/NTupleProd/commit/1a858c293c6c8d447877f7f5c0e59a977787a676)

**Comment by calcuttj** [comment]
Question on this: 

the individual files will of course have their own memory/cpu/walltime. What about the final merged file?
